### ISSUE TITLE
When I run example-project on a Japanese e-reader+, the words “sprite demo” are not displayed correctly.

### ISSUE THREAD

**Issue by owasikohu** [AkBKukU/e-reader-dev#3]
Do you know about it?

**Comment by city41** [comment]
This is because the Japanese E-Reader does not support English characters. It only supports Japanese with the Shift-JIS encoding.

Here is a very simple example of using Shift-JIS.

![ereaderJPN-4](https://github.com/user-attachments/assets/4a79637f-041c-4d33-b814-d94d381087ea)

Instead of doing this

```c
ERAPI_DrawText(chooser, 0, 0, "    Sprite:");
```

It'd have to be something like

```c
u8 helloInShiftJis[] = { 130,177,130,241,130,201,130,191,130,205 };
ERAPI_DrawText(chooser, 0, 0, helloInShiftJis);
```

Hopefully there is a better way to do Shift-JIS strings in C, but I don't know how.

**Comment by city41** [comment]
oh yeah, @owasikohu thanks again for helping me with the Japanese translation for Solitaire :)

**Comment by owasikohu** [comment]
Thank  you.

**Comment by city41** [comment]
@owasikohu I was not entirely correct. The Japanese E-Reader can display ascii characters.

Here is a rough ts function for converting from ascii to shift-jis

```
const jistable = [
  0x40, 0x49, 0x00, 0x94, 0x90, 0x93, 0x95, 0x66, 0x69, 0x6a, 0x96, 0x7b, 0x43,
  0x5d, 0x44, 0x5e, 0x4f, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58,
  0x46, 0x47, 0x83, 0x81, 0x84, 0x48, 0x97, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65,
  0x66, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72,
  0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x6d, 0x5f, 0x6e, 0x4f, 0x51, 0x4d,
  0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d,
  0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a,
  0x6f, 0x62, 0x70, 0x60,
];

function asciiInShiftJis(str: string): number[] {
  const output: number[] = [];

  for (let i = 0; i < str.length; ++i) {
    if (
      (str[i] >= "a" && str[i] <= "z") ||
      (str[i] >= "A" && str[i] <= "Z") ||
      (str[i] >= "0" && str[i] <= "9")
    ) {
      output[i * 2] = 0x82;
      output[i * 2 + 1] = jistable[str.charCodeAt(i) - 0x20];
      
    }
  }

  return output;
}
```

So "hello" is `0x82,0x88,0x82,0x85,0x82,0x8c,0x82,0x8c,0x82,0x8f`

This is running on the Japanese E-reader+

![ereaderJPN-0](https://github.com/user-attachments/assets/f3c89f98-58a9-48d8-9faf-cf78c0ae0135)
